package com.tcg.arena.model;

public enum ActivityType {
    CARD_ADDED_TO_COLLECTION,
    CARD_REMOVED_FROM_COLLECTION,
    DECK_CREATED,
    DECK_UPDATED,
    DECK_DELETED,
    TOURNAMENT_JOINED,
    TOURNAMENT_LEFT,
    TOURNAMENT_WON,
    TOURNAMENT_LOST,
    SHOP_FAVORITED,
    SHOP_UNFAVORITED,
    USER_REGISTERED,
    USER_PROFILE_UPDATED,
    USER_PREFERENCES_UPDATED,
    CARD_TRADE_INITIATED,
    CARD_TRADE_COMPLETED,
    POINTS_EARNED,
    REWARD_REDEEMED,
    DECK_LIKED,
    PROFILE_APPRECIATED
}